# Generated by Django 4.0.1 on 2022-01-08 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0003_ad_expirationdate_ad_projectstartdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 7, 24, 39, 991416, tzinfo=utc), verbose_name='expiration date (of ad)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='projectStartDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='project started (date)'),
        ),
    ]
