# Generated by Django 4.0.1 on 2022-01-09 21:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0005_comment_alter_ad_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codermatch.ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commentText',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='publication date (of comment)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 21, 41, 11, 903602, tzinfo=utc), verbose_name='expiration date (of ad)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='pubDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publication date (of ad)'),
        ),
    ]
