# Generated by Django 4.0.1 on 2022-01-10 07:50

import codermatch.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0006_comment_ad_comment_commenttext_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationDate',
            field=models.DateTimeField(default=codermatch.models.Ad.in30Days, verbose_name='expiration date (of ad)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='codermatch.ad'),
        ),
    ]
