# Generated by Django 4.0.1 on 2022-01-10 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0007_alter_ad_expirationdate_alter_comment_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 7, 56, 58, 875233, tzinfo=utc), verbose_name='expiration date (of ad)'),
        ),
    ]
