# Generated by Django 4.0.1 on 2022-01-10 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0008_alter_ad_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 7, 59, 54, 451245, tzinfo=utc), verbose_name='expiration date (of ad)'),
        ),
    ]
