# Generated by Django 4.0.1 on 2022-01-10 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0011_ad_likes_alter_ad_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 8, 17, 46, 963635, tzinfo=utc), verbose_name='expiration date (of ad)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='projectDescription',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentText',
            field=models.TextField(max_length=1000),
        ),
    ]
