# Generated by Django 4.0.1 on 2022-01-12 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0013_alter_ad_expirationdate_alter_comment_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='expirationDate',
        ),
        migrations.AddField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 7, 30, 44, 36332, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
