# Generated by Django 4.0.1 on 2022-01-14 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0015_alter_ad_expirationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 9, 47, 51, 697467, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
