# Generated by Django 4.0.1 on 2022-01-18 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0022_alter_ad_expirationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 6, 29, 53, 825323, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
