# Generated by Django 4.0.1 on 2022-01-21 07:21

import codermatch.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0026_alter_ad_expirationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='creatorName',
            field=models.CharField(default='default creator name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=codermatch.models.Ad.in30Days, verbose_name='expiration time (of ad)'),
        ),
    ]
