# Generated by Django 4.0.1 on 2022-01-24 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0028_alter_ad_expirationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 7, 49, 58, 710281, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
