# Generated by Django 4.0.1 on 2022-02-01 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0032_alter_ad_expirationtime_alter_ad_projectstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 11, 31, 57, 978251, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='projectStartDate',
            field=models.DateField(blank=True, default=False, verbose_name='project started (date)'),
            preserve_default=False,
        ),
    ]
