# Generated by Django 4.0.1 on 2022-02-08 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0033_alter_ad_expirationtime_alter_ad_projectstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 9, 40, 4, 255859, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
