# Generated by Django 4.0.1 on 2022-02-08 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0035_alter_ad_expirationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='expirationTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 10, 56, 52, 396484, tzinfo=utc), verbose_name='expiration time (of ad)'),
        ),
    ]
