# Generated by Django 4.0.1 on 2022-02-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0043_alter_ad_projectstartdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='projectDescription',
            new_name='adDescription',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='projectTitle',
            new_name='adTitle',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='projectStartDate',
        ),
        migrations.AddField(
            model_name='ad',
            name='adPurpose',
            field=models.IntegerField(choices=[(1, 'Present A Project'), (2, 'Find A Project'), (3, 'Something Else')], default=1),
        ),
    ]
