# Generated by Django 4.0.1 on 2022-01-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='projectStartDate',
        ),
    ]
