# Generated by Django 4.0.1 on 2022-01-08 07:53

import codermatch.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0004_alter_ad_expirationdate_alter_ad_projectstartdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ad',
            name='expirationDate',
            field=models.DateTimeField(default=codermatch.models.Ad.in30Days, verbose_name='expiration date (of ad)'),
        ),
    ]
