# Generated by Django 4.0.1 on 2022-02-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codermatch', '0044_rename_projectdescription_ad_addescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='creatorEmail',
            field=models.EmailField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
